FROM launcher.gcr.io/google/ubuntu16_04

RUN apt-get -y update
RUN apt-get -y install gcc wget ca-certificates software-properties-common

    # Install Python 3.7
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get -y update && \
    apt-get -y install python3.7

    # Install Git >2.0.1
RUN add-apt-repository ppa:git-core/ppa && \
    apt-get -y update && \
    apt-get -y install git

    # Setup Google Cloud SDK (latest)
RUN mkdir -p /builder
RUN wget -qO- https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz | tar zxv -C /builder && \
    CLOUDSDK_PYTHON="python3.7" /builder/google-cloud-sdk/install.sh --usage-reporting=false \
        --bash-completion=false \
        --disable-installation-options
    # install crcmod: https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod
RUN apt-get purge -y python2.7-minimal
RUN apt-get -y remove 'python3.*'
RUN apt-get -y update
RUN apt-get -y install build-essential libpq-dev libssl-dev openssl libffi-dev zlib1g-dev
RUN apt-get -y install python3-pip python3.7-dev
RUN apt-get -y install python3.7
RUN python3 -m pip install --upgrade pip && \
    pip3 install -U crcmod && pip3 install Flask==1.1.2 tensorflow==2.2.0 stocker

    # Clean up
RUN apt-get -y remove gcc python-dev python-setuptools wget && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf ~/.config/gcloud

COPY notice.sh /builder

ENV PATH=/builder/google-cloud-sdk/bin/:$PATH
RUN git config --system credential.helper gcloud.sh

ENTRYPOINT ["/builder/notice.sh"]
