FROM launcher.gcr.io/google/ubuntu16_04

RUN apt-get -y update
RUN apt-get -y install gcc wget ca-certificates \
       # These are necessary for add-apt-respository
       software-properties-common python-software-properties

    # Install Python 3.7
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get -y update && \
    apt-get -y install python3.7

    # Install Git >2.0.1
RUN add-apt-repository ppa:git-core/ppa && \
    apt-get -y update && \
    apt-get -y install git

    # Setup Google Cloud SDK (latest)
RUN mkdir -p /builder
RUN wget -qO- https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz | tar zxv -C /builder && \
    CLOUDSDK_PYTHON="python3.7" /builder/google-cloud-sdk/install.sh --usage-reporting=false \
        --bash-completion=false \
        --disable-installation-options
    # install crcmod: https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod
RUN apt-get -y install python3-pip && pip3 install --upgrade pip && pip3 install -r requirements.txt && \
    pip3 install -U crcmod

    # Clean up
RUN apt-get -y remove gcc python-dev python-setuptools wget && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf ~/.config/gcloud

COPY notice.sh /builder

ENV PATH=/builder/google-cloud-sdk/bin/:$PATH
RUN git config --system credential.helper gcloud.sh

ENTRYPOINT ["/builder/notice.sh"]
